### ISSUE TITLE
Feature Request: key mapping changed notifications

### ISSUE THREAD

**Issue by G-M0N3Y-2503** [houmain/keymapper#91] opened 2023-12-18 11:04 UTC
It would be good to be able to configure a system notification to pop up that helps explain the key map that is active.

For me the notible key maps change when any of the virtual keys are pressed or when a context change matches a new block.

Perhaps a good first step for the notification message would be the virtual keys alias and the context values.

### Linux Workaround
```
[class=/chrome/i title=/some website/i device="Razer Razer Basilisk V3 Pro"]
Modified = Virtual0
!Modified ControlLeft   >> Modified $(notify-send -t 500 -a "keymapper" "Not Modified") ^
Modified{ControlLeft}   >> Modified $(notify-send -t 500 -a "keymapper" "Modified") ^
!Modified ButtonForward >> A
Modified{ButtonForward} >> B
```

**Comment by G-M0N3Y-2503** [comment] 2023-12-19 01:12
Maybe for the Virtual key senario more thought is required.
What works for me on Linux is the following:

```
[device="Razer Razer Basilisk V3 Pro"]
VolumeProfile = Virtual1
MediaProfile = Virtual2
Profiles = MediaProfile | VolumeProfile

[system="Linux" device="Razer Razer Basilisk V3 Pro"]
SetNoneProfile      =               $(notify-send -t 500 -a "keymapper" "Profile:\n [None] Volume  Media") ^
SetVolumeProfile    = VolumeProfile $(notify-send -t 500 -a "keymapper" "Profile:\n  None [Volume] Media") ^
SetMedifProfile     = MediaProfile  $(notify-send -t 500 -a "keymapper" "Profile:\n  None  Volume [Media]") ^

# Reddit

[modifier="!Profiles" class=/chrome/i title=/reddit/i device="Razer Razer Basilisk V3 Pro"]
ButtonForward   >> J
ButtonBack      >> K

# Default

[device="Razer Razer Basilisk V3 Pro"]
!Profiles ControlLeft       >> SetVolumeProfile
VolumeProfile{ControlLeft}  >> VolumeProfile SetMedifProfile
MediaProfile{ControlLeft}   >> MediaProfile SetNoneProfile

[modifier="VolumeProfile" device="Razer Razer Basilisk V3 Pro"]
ButtonForward   >> AudioVolumeUp
ButtonBack      >> AudioVolumeDown
AltLeft         >> (Meta){AudioVolumeMute}

[modifier="MediaProfile" device="Razer Razer Basilisk V3 Pro"]
ButtonForward   >> MediaTrackNext
ButtonBack      >> MediaTrackPrevious
AltLeft         >> MediaPlayPause

[device="Razer Razer Basilisk V3 Pro"]
AltLeft >> LaunchApp1
Any     >> Any
```

So It notifies me exactly what mapping I have for the virtual keys but not when I am on Reddit vs some other site.

**Comment by ristomatti** [comment] 2023-12-19 18:52
@G-M0N3Y-2503 Cool trick, thanks for sharing!

**Comment by G-M0N3Y-2503** [comment] 2024-02-04 07:11
For Windows and Linux the following gets across the line for the notification part at least.
```
MediaProfileMsg  = "keymapper" "Profile:  None  Volume [Media]"
VolumeProfileMsg = "keymapper" "Profile:  None [Volume] Media"
NoneProfileMsg   = "keymapper" "Profile: [None] Volume  Media"

[system="Linux" device="Razer Razer Basilisk V3 Pro"]
MediaProfileNotify  = $(notify-send -t 500 -a MediaProfileMsg) ^
VolumeProfileNotify = $(notify-send -t 500 -a VolumeProfileMsg) ^
NoneProfileNotify   = $(notify-send -t 500 -a NoneProfileMsg) ^

[system="Windows"]
MediaProfileNotify  = $(msg.exe * /TIME:1 MediaProfileMsg) ^
VolumeProfileNotify = $(msg.exe * /TIME:1 VolumeProfileMsg) ^
NoneProfileNotify   = $(msg.exe * /TIME:1 NoneProfileMsg) ^
```

No device filter on Windows which makes it difficult for cross-platform.

**Comment by G-M0N3Y-2503** [comment] 2024-02-04 11:15
That sounds awesome!
It'd be good to explicitly know when you're changing context!

But to avoid conflation on one part of my shown config, just to be safe.
It allows me to change the map tempararily while in a different context, like changing music while in VSCode where I more often use the default map.
These changes will help clean that up a and let me have context specific maps to cycle through.
But just noting it is different.

**Comment by houmain** [comment] 2024-02-15 16:30
This is already testable, if you are willing to build the `next` branch from source.
It is not yet documented but this is the config I used for testing:
```
log = $(print "$0" >> ~/keymapper.log)
context = 50ms log["entered $0"] ^ log["left $0"]

[title="GPUpad"]
ContextActive >> context["GPUpad"]

[title="Thunar"]
ContextActive >> context["Thunar"]
```
It should be quite self-explanatory. It logs whenever one of the applications gets/loses focus to a file.

**Comment by ristomatti** [comment] 2024-02-15 17:35
@houmain I tried building it on my Ubuntu Focal based system but the build fails. I guess my toolchain is too obsolete?

```
$ cmake --version
cmake version 3.25.0

$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
```

Error:

```
+ cmake -B ./build -DCMAKE_INSTALL_PREFIX=dist
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ristomatti/src/keymapper/build
+ cmake --build ./build --config Release
[  3%] Building CXX object CMakeFiles/keymapper.dir/src/config/ParseConfig.cpp.o
/home/ristomatti/src/keymapper/src/config/ParseConfig.cpp: In member function ‘std::string ParseConfig::preprocess_ident(std::string) const’:
/home/ristomatti/src/keymapper/src/config/ParseConfig.cpp:466:65: error: could not convert ‘{ident.std::__cxx11::basic_string<char>::begin().__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >::operator+(((__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >::difference_type)pos)).__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >::operator+(1), ident.std::__cxx11::basic_string<char>::end()}’ from ‘<brace-enclosed initializer list>’ to ‘std::string_view’ {aka ‘std::basic_string_view<char>’}
  466 |       get_argument_list({ ident.begin() + pos + 1, ident.end() }));
      |                                                                 ^
      |                                                                 |
      |                                                                 <brace-enclosed initializer list>
In file included from /usr/include/x86_64-linux-gnu/c++/9/bits/c++allocator.h:33,
                 from /usr/include/c++/9/bits/allocator.h:46,
                 from /usr/include/c++/9/string:41,
                 from /home/ristomatti/src/keymapper/src/runtime/Key.h:3,
                 from /home/ristomatti/src/keymapper/src/runtime/KeyEvent.h:3,
                 from /home/ristomatti/src/keymapper/src/config/ParseConfig.h:3,
                 from /home/ristomatti/src/keymapper/src/config/ParseConfig.cpp:2:
/usr/include/c++/9/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = std::basic_string_view<char>; _Args = {const char*&, const char*}; _Tp = std::basic_string_view<char>]’:
/usr/include/c++/9/bits/alloc_traits.h:483:4:   required from ‘static void std::allocator_traits<std::allocator<_CharT> >::construct(std::allocator_traits<std::allocator<_CharT> >::allocator_type&, _Up*, _Args&& ...) [with _Up = std::basic_string_view<char>; _Args = {const char*&, const char*}; _Tp = std::basic_string_view<char>; std::allocator_traits<std::allocator<_CharT> >::allocator_type = std::allocator<std::basic_string_view<char> >]’
/usr/include/c++/9/bits/vector.tcc:115:30:   required from ‘std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {const char*&, const char*}; _Tp = std::basic_string_view<char>; _Alloc = std::allocator<std::basic_string_view<char> >; std::vector<_Tp, _Alloc>::reference = std::basic_string_view<char>&]’
/home/ristomatti/src/keymapper/src/config/ParseConfig.cpp:80:62:   required from here
/usr/include/c++/9/ext/new_allocator.h:146:4: error: invalid conversion from ‘const char*’ to ‘std::basic_string_view<char>::size_type’ {aka ‘long unsigned int’} [-fpermissive]
  146 |  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |    |
      |    const char*
In file included from /usr/include/c++/9/bits/basic_string.h:48,
                 from /usr/include/c++/9/string:55,
                 from /home/ristomatti/src/keymapper/src/runtime/Key.h:3,
                 from /home/ristomatti/src/keymapper/src/runtime/KeyEvent.h:3,
                 from /home/ristomatti/src/keymapper/src/config/ParseConfig.h:3,
                 from /home/ristomatti/src/keymapper/src/config/ParseConfig.cpp:2:
/usr/include/c++/9/string_view:129:56: note:   initializing argument 2 of ‘constexpr std::basic_string_view<_CharT, _Traits>::basic_string_view(const _CharT*, std::basic_string_view<_CharT, _Traits>::size_type) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_string_view<_CharT, _Traits>::size_type = long unsigned int]’
  129 |       basic_string_view(const _CharT* __str, size_type __len) noexcept
      |                                              ~~~~~~~~~~^~~~~
make[2]: *** [CMakeFiles/keymapper.dir/build.make:272: CMakeFiles/keymapper.dir/src/config/ParseConfig.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/keymapper.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by houmain** [comment] 2024-02-15 18:02
Oops, I unintentionally used a C++20 feature. This is fixed now. Please try again.

**Comment by houmain** [comment] 2024-02-15 18:09
Here is another example, with multiple arguments:
```
modify = $0{ $1 }
A >> modify[ShiftLeft, X]
```

**Comment by ristomatti** [comment] 2024-02-15 19:02
So nice! This will definitely help with debugging. I can get `ContextActive` to trigger on `class`, `title` and `modifier` scoped contexts but not on a `device` scoped context. Is this a bug or expected behavior

Test config below. When the window gets focused "entered kitty default", but if I press F12, "k15" gets typed.

```
log = $(echo "$0" >> ~/tmp/keymapper.log)
context = 50ms log["entered $0"] ^ log["left $0"]

KeyboardK15Pro = /Keychron K15 Pro Keyboard$/i

[device=KeyboardK15Pro class="kitty"]
  ContextActive >> context["kitty k15 pro"]
  F12 >> 'k15'

[class="kitty"]
  ContextActive >> context["kitty default"]
  F12 >> 'default'
```

**Comment by ristomatti** [comment] 2024-02-15 19:19
> Here is another example, with multiple arguments:
> 
> ```
> modify = $0{ $1 }
> A >> modify[ShiftLeft, X]
> ```

Multiple arguments seems to work also,  perfect.

I see this example uncovered another yet undocumented and also rather unexpected feature! Do you have a specific use case in mind for this? My imagination is lacking with this one. :thinking:

**Comment by houmain** [comment] 2024-02-15 20:02
> ... but not on a `device` scoped context. Is this a bug or expected behavior?

That is not intentional. I will fix that soon. Thanks!

> I see this example uncovered another yet undocumented and also rather unexpected feature!

It is actually not another new feature. Just the possibility to pass arguments to aliases/macros.

>  Do you have a specific use case in mind for this? My imagination is lacking with this one. 🤔

Not yet, maybe someone finds another use case beside debugging. 😄

**Comment by ristomatti** [comment] 2024-03-04 01:44
@houmain I came across a bug with the parameterized aliases. The parameter apparently cannot be an alias itself.

Repro with some context of what I'm doing:

```ini
log = $(echo "$0" >> ~/tmp/keymapper.log)

# Logitech G502 X
ButtonSide      = 277

DoubleTap       = $0 !250ms $0

[default]
  ButtonSideDouble  = ButtonSide !200ms ButtonSide

  ButtonForward{150ms}    >> log["mouse_drag"]
  ButtonBack{150ms}       >> log["mouse_drag_resize"]
  # ButtonSideDouble      >> log["wm_float_window"]       # OK
  # DoubleTap[277]        >> log["wm_float_window"]       # OK
  DoubleTap[ButtonSide]   >> log["wm_float_window"]       # Invalid key "ButtonSide"
  ButtonSide              >>

[modifier="ButtonSide"]
  DoubleTap[ButtonLeft]   >> log["wm_resize_window"]      # OK
  ButtonLeft              >> log["wm_center_window"]
  DoubleTap[ButtonRight]  >> log["wm_close_window"]       # OK
  ButtonRight             >> log["wm_resize_window_wide"]
  ButtonMiddle            >> log["wm_sticky_toggle"]
```

**Comment by houmain** [comment] 2024-03-16 13:37
@ristomatti
Aliases should now work as parameters.
Also the ContextActive in device contexts should work now.

**Comment by ristomatti** [comment] 2024-03-17 23:43
Sorry to report but the fix doesn't seem to work fully and the changes caused some regression with the mappings the above example config was based on. The actual snippet from my config:

```ini
ButtonSide      = 277

[device=MouseG502X]
  ButtonSideDouble  = ButtonSide !200ms ButtonSide

  ButtonForward{150ms}    >> mouse_drag
  ButtonBack{150ms}       >> mouse_drag_resize
  # ButtonSideDouble        >> wm_float_window
  ButtonSideDouble        >> log["wm_float_window"]  # <- modified for testing
  ButtonSide              >>

[device=MouseG502X modifier="ButtonSide"]
  # Added as a test
  ContextActive >> log["MouseG502X ButtonSide"]      # <- added for testing

  DoubleTap[ButtonLeft]   >> wm_resize_window
  ButtonLeft              >> wm_center_window
  # DoubleTap[ButtonRight]  >> wm_close_window
  DoubleTap[ButtonRight]  >> log["wm_close_window"]  # <- modified for testing

  ButtonRight             >> wm_resize_window_wide
  ButtonMiddle            >> wm_sticky_toggle

# ... lots of other config ...

[default]
  mouse_drag                  >> (AltLeft ButtonLeft)
  mouse_drag_resize           >> (AltLeft ButtonRight)

  wm_resize_window            >> $(i3-msg "resize set 1000px 1200px") ^
  wm_resize_window_wide       >> $(i3-msg "resize set 1800px 1200px") ^
  wm_center_window            >> $(i3-msg "move absolute position center") ^
  wm_close_window             >> $(i3-msg '[con_id="__focused__"] kill') ^
  wm_float_window             >> $(i3-msg "floating toggle") ^
  wm_sticky_toggle            >> $(i3-msg "sticky toggle") ^
```

These mappings stopped working:

```ini
  ButtonSideDouble        >> wm_float_window
  ButtonForward{150ms}    >> mouse_drag
  ButtonBack{150ms}       >> mouse_drag_resize
```

Neither of these seem to trigger:

```ini
[device=MouseG502X]
  ButtonSideDouble        >> log["wm_float_window"]

[device=MouseG502X modifier="ButtonSide"]
  ContextActive >> log["MouseG502X ButtonSide"]
```

This however does work as expected but it did previously as well.

```ini
  DoubleTap[ButtonRight]  >> log["wm_close_window"]
```

**Comment by ristomatti** [comment] 2024-03-18 01:12
> I incremented the major version since I refactored the code a lot

I can see that. https://github.com/houmain/keymapper/compare/3.5.3...next :exploding_head:

**Comment by houmain** [comment] 2024-03-18 19:01
Thanks for trying it out so quickly. I am glad I did not release it yet. I will analyze this asap!

**Comment by ristomatti** [comment] 2024-03-22 12:27
I tried this again with the new updates you mentioned here https://github.com/houmain/keymapper/issues/105#issuecomment-2008003564.

I was able to get `ContextActive` to trigger from this:

```ini
[device=MouseG502X modifier="ButtonSide"]
  ContextActive           >> log["MouseG502X ButtonSide"]
```

I don't know if it's got anything to do with the changes but I got it to trigger by a slight modification below. It seemed to have the downside I couldn't get a mapping like `ButtonSide !200ms ButtonSide >> do_stuff` to work.

```ini
ButtonSideMod   = Virtual7

[device=MouseG502X]
  ContextActive >> context["MouseG502X"]
  ButtonSide    >> ButtonSideMod ^ ButtonSideMod

[device=MouseG502X modifier="ButtonSideMod"]
  ContextActive >> context["MouseG502X ButtonSide"]
```

I did some more testing/debugging around the mouse button mappings. The remaining issue is that my mappings for window move/drag from any part of the window when holding mouse back/forward buttons does not work anymore:

```ini
# [device=MouseG502X]  <- commented out for this to work as a test config 
[default]
  ButtonForward{150ms}    >> mouse_drag
  ButtonBack{150ms}       >> mouse_drag_resize

  # This would work but it'd break normal use as back/forward buttons 
  # ButtonForward         >> mouse_drag
  # ButtonBack            >> mouse_drag_resize

[default]
  mouse_drag              >> (AltLeft ButtonLeft)
  mouse_drag_resize       >> (AltLeft ButtonRight)
```

**Comment by houmain** [comment] 2024-03-22 20:48
I think I could reproduce it with this configuration. There is still a problem when a key is used at the same time in a context modifier and has a timeout:
```
X{!1000ms} >> B

[modifier="X"]
  ContextActive >> A ^
```

**Comment by ristomatti** [comment] 2024-03-22 22:50
We're you able to reproduce the last example about the mouse keys held down? I forgot to include this minimum config I was able to reproduce it. It seems to be affect any mapping that relies on holding a button down:

```ini
1{250ms} >> 2
```

Previously this would allow using `1` as normal but start repeating `2` after 150ms.

**Comment by houmain** [comment] 2024-03-28 17:42
Hi ristomatti,
With the latest commits I can no longer reproduce any problem. I tested it with the configurations above and this one:
```
log = $(notify-send -t 2000 -a "keymapper" "$0")

MouseG502X      = /G300/i
ButtonSide      = ButtonBack

[device=MouseG502X]

  ButtonSideDouble  = ButtonSide !200ms ButtonSide
  ButtonSideDouble        >> log["wm_float_window"]

[device=MouseG502X modifier="ButtonBack"]
  ContextActive           >> log["ButtonSide"]
```
Could you please also give the latest version an try?

**Comment by ristomatti** [comment] 2024-03-30 19:27
I'm still seeing a change with the mouse handling, e.g. my old config doesn't work. I have not yet pinpointed if it's due to relying on some undocumented behavior. Here's an example config with only the bits of config affected:

```ini
# Debug logging
log        = $(echo "$0" >> ~/tmp/keymapper.log)
context    = 50ms log["entered $0"] ^ log["left $0"]

# Custom keys
ButtonSide = 277

# Context matchers
Mouse      = /Mouse|Logitech USB Receiver|G502/i
MouseG502X = /Logitech USB Receiver|G502 X LIGHTSPEED/i

# Pameterized aliases
DoubleTap  = $0 !250ms $0{!250ms}
Hold       = $0{200ms}

[device=Mouse]
  ContextActive           >> context["Mouse"]              # triggers, previosly didn't

  ButtonForward{150ms}    >> mouse_drag                    # doesn't trigger
  ButtonBack{150ms}       >> mouse_drag_resize             # doesn't trigger

[device=MouseG502X modifier="ButtonSide"]
  ContextActive           >> context["G502X ButtonSide"]   # triggers, previosly didn't

  DoubleTap[ButtonLeft]   >> log["wm_resize_window"]       # triggers
  DoubleTap[ButtonRight]  >> log["wm_close_window"]        # triggers
  Hold[ButtonMiddle]      >> log["wm_sticky_toggle"]       # doesn't trigger

  ButtonLeft              >> log["wm_center_window"]       # doesn't trigger
  ButtonRight             >> log["wm_resize_window_wide"]  # doesn't trigger
  ButtonMiddle            >> log["wm_float_window"]        # triggers

[default]
  mouse_drag              >> (AltLeft ButtonLeft)
  mouse_drag_resize       >> (AltLeft ButtonRight)
```

Previously all worked except the device context `ContextActive` logs.

**Comment by ristomatti** [comment] 2024-03-30 19:30
I just noticed that that if I don't define a separate `ButtonSide` context, these both trigger.

```ini
[device=MouseG502X]
  ButtonSide{DoubleTap[ButtonLeft]}  >> log["wm_resize_window"]
  ButtonSide{ButtonLeft}             >> log["wm_center_window"] 
```

**Comment by ristomatti** [comment] 2024-03-30 19:37
Further findings, this config dones't work either for me:

```ini
log  = $(echo "$0" >> ~/tmp/keymapper.log)

Hold = $0{200ms}

Hold[F4] >> log["F4 held"]  # doesn't trigger
```

**Comment by ristomatti** [comment] 2024-03-31 22:47
Actually it seems key hold mappings do not work at all. Even this does not work on my system. :thinking: 

```ini
A{200ms} >> B
```

**Comment by ristomatti** [comment] 2024-04-01 01:01
@houmain Out of curiosity, I traced the commit after which `X{200ms} >> Y` mappings stop working. It's this one https://github.com/houmain/keymapper/commit/0979310df0264afefab40ce0f85fd623da9394c3 which first introduced `keymapperctl`.

**Comment by houmain** [comment] 2024-04-07 18:10
Sorry for the late reply! I was AFK this week. 
The last commit should fix the problem.

**Comment by houmain** [comment] 2024-04-09 14:55
I tested your configuration and found another bug, thanks!
I am again quite confident that it should work now.

**Comment by ristomatti** [comment] 2024-04-09 16:30
Great work! Everything the above config works and so does every other mapping I've tried so far. I found one regression though unless it's by design in the new version. Aliases don't work within shell commands. E.g.

```ini
LOG_FILE = "$HOME/tmp/keymapper.log"

log = $(echo "$0" >> LOG_FILE)
# ...various other commands that log to the same file
```

Now the logs go to `~/LOG_FILE`. I don't have that many aliases I use as variables on the commands so I can just inline them. I have a vague memory you at some point added a workaround to prevent alias substitution within quotes(?)

**Comment by ristomatti** [comment] 2024-04-09 16:36
Similarly I had this state indicator logic (which I'm definitely going to redo using `keymapperctl`)

```ini
# Create state directory if it doesn't exist
ensureStateDirExists       = test -f STATE_DIR || mkdir -p STATE_DIR

# Status bar input mode indicator handling
auto_shift_status_on       = $(ensureStateDirExists && touch AUTO_SHIFT_FILE)
auto_shift_status_off      = $(test -f AUTO_SHIFT_FILE && rm AUTO_SHIFT_FILE)

direct_umlauts_status_on   = $(ensureStateDirExists && touch DIRECT_UMLAUTS_FILE)
direct_umlauts_status_off  = $(test -f DIRECT_UMLAUTS_FILE && rm DIRECT_UMLAUTS_FILE)

caps_word_status_on        = $(ensureStateDirExists && touch CAPS_WORD_FILE)
caps_word_status_off       = $(test -f CAPS_WORD_FILE && rm CAPS_WORD_FILE)
```

Here `ensureStateDirExists` gives "command not found" error when running with verbose logging.

**Comment by ristomatti** [comment] 2024-04-09 16:59
Now with everything inlined, the indicators work as well. 🙂

**Comment by houmain** [comment] 2024-04-09 17:39
I restored the substitution within terminal commands.

**Comment by ristomatti** [comment] 2024-04-09 18:31
Confirm working again. Your reaction times are insane! :zap:

**Closed** 2024-04-10 18:36 UTC
