### ISSUE TITLE
Can't parse config with output characters

### ISSUE THREAD

**Issue by Zireael07** [houmain/keymapper#123] opened 2024-04-01 13:28 UTC
Both git from roughly a year ago and 4.0.0 have the same issue.

AltRight{A} >> 'ae'

Results in Key name expected at ''' in line 56

EDIT: Same problem with the print = $(echo $0 $1 >> ~\keymapper.txt)
F1 >> print["pressed the key", F1]

example from README.

surprisingly, e y >> $(echo e y >> ~\keymapper.txt) works

**Comment by kbilsted** [comment] 2024-04-07 10:21
I just tried your example and it works on windows 11
What OS are you on?
Post full config please

**Comment by houmain** [comment] 2024-04-07 18:26
I cannot reproduce it on Linux either. Could you please create a minimal configuration which leads to this message?

> Both git from roughly a year ago and 4.0.0 have the same issue.
The string typing feature was added more recently (in November). Before that strings were only allowed in terminal commands.

**Comment by kbilsted** [comment] 2024-04-07 19:12
Try just with `AltRight{A} >> 'ae'`

**Comment by Zireael07** [comment] 2024-04-08 16:08
> The character typing feature was added more recently (in November).

If the case is that the feature isn't available in 4.0.0, it should be made clear in README.

**Comment by kbilsted** [comment] 2024-04-08 16:26
It is supported. 

Try a config with just that one line and make sure to store as ascii I'm not sure weird utf formats are supported

**Comment by houmain** [comment] 2024-04-08 17:56
> make sure to store as ascii I'm not sure weird utf formats are supported

Very good point! I have not thought about that. Only UTF-8 is supported. I should add that to the README and see if I can detect mojibake.

**Comment by Zireael07** [comment] 2024-04-08 19:09
I am trying to create a steno/artsey hybrid, so a config with just that one line won't cut it. It needs to work as part of a larger setup

**Comment by kbilsted** [comment] 2024-04-08 20:24
@Zireael07  Trust the process. You are the one reaching out. We are trying to debug your problem. Cut down the problem till we isolate the issue.

**Comment by houmain** [comment] 2024-04-09 05:03
Ideally you could attach a minimal configuration which raises this error message as a file. So a potentially problematic encoding is preserved.

**Comment by Zireael07** [comment] 2024-04-09 10:22
Gotcha.

I tried remaking step by step and now it works? Both files are attached in case you find the difference somehow - orig is the one that didn't work.

My text editors (Kate and open source version of VS Code) agree that both files are UTF-8

[keymapper.conf.zip](https://github.com/houmain/keymapper/files/14917299/keymapper.conf.zip)

**Comment by ristomatti** [comment] 2024-04-09 11:35
![image](https://github.com/houmain/keymapper/assets/9029939/c113af2f-a544-459e-b638-abc0b1726707)

**Comment by Zireael07** [comment] 2024-04-09 12:04
The obviously different part was all commented out in the original so shouldn't matter. As you see the beginning is the same except the problematic lines were commented out in the original and are NOT in the new one

**Comment by houmain** [comment] 2024-04-11 17:33
So this problem is currently not reproducible? Then I would close the issue for now.

**Comment by Zireael07** [comment] 2024-04-11 18:01
Yeah I'll do it, since the most likely culprit is some hidden character or something. Leaving this comment as a request for such an enhancement

**Comment by Zireael07** [comment] 2024-04-23 15:39
Bug struck again as soon as I edited the copied (working) config to introduce a change. Kate insists the file is normal UTF-8, BOM off.

**Comment by houmain** [comment] 2024-04-23 15:49
So now you have a config where this problem is reproducible? Can you please upload it?

**Comment by Zireael07** [comment] 2024-04-23 17:55
[keymapper.conf.zip](https://github.com/houmain/keymapper/files/15080927/keymapper.conf.zip)

Uploaded, although it won't probably be of much use since the changes consisted of: adding config for my new numpad (that's what the "SZH usb keyboard" really is) AND commenting out the lines that caused the bug to appear

**Comment by ristomatti** [comment] 2024-04-23 23:54
Do you mean a bug in how the mappings behave or Keymapper saying the config is not valid? I spotted only a couple of commented out lines and none of them caused an error.

Was this by any chance the line you were referring to?

```ini
[device="SZH usb keyboard"]
   #Any >> O
```

If it's this and you're on Linux, I bumped into an issue with something very similar. A big portion of my mappings stopped working but I got it fixed. The issue you're having might be completely different but I'll describe what I ran across in case it happens to be the same.

In my case, this is how the device shows up:

```
$ xinput list | grep SINO
⎜   ↳ SINO WEALTH Gaming KB  Consumer Control 	id=11	[slave  pointer  (2)]
⎜   ↳ SINO WEALTH Gaming KB  Mouse            	id=32	[slave  pointer  (2)]
    ↳ SINO WEALTH Gaming KB                   	id=9	[slave  keyboard (3)]
    ↳ SINO WEALTH Gaming KB  System Control   	id=10	[slave  keyboard (3)]
    ↳ SINO WEALTH Gaming KB  Consumer Control 	id=12	[slave  keyboard (3)]
    ↳ SINO WEALTH Gaming KB  Keyboard         	id=13	[slave  keyboard (3)]
```

Initially I had it set up like this:

```ini
NumpadApayado = /SINO WEALTH Gaming KB/i

# ... lots of other config

[device = NumpadApayado]
  # ... a few mappings
  Any >> Any

# ... lots of other config, some of them not working anymore
```

After looking at the `xinput` listing again, I realized the `Any` was grabbing other devices as well. I don't know what actually causes this, but it seemed odd* that the numpad registers also as a pointer device. The issue got fixed when I then changed the device matcher to match only the keyboard devices:

```  
NumpadApayado = /SINO WEALTH Gaming (KB |KB  Keyboard)$/i
```
 
*) The reason is likely not that odd. I'm guessing it just contains some chip that also supports that. The listing looks awfully similar to how my Keychron keyboard shows up in the listing:

```
$ xinput | grep Keychron
⎜   ↳ Keychron Keychron K15 Pro Consumer Control	id=21	[slave  pointer  (2)]
⎜   ↳ Keychron Keychron K15 Pro Mouse         	id=24	[slave  pointer  (2)]
    ↳ Keychron Keychron K15 Pro               	id=19	[slave  keyboard (3)]
    ↳ Keychron Keychron K15 Pro Keyboard      	id=20	[slave  keyboard (3)]
    ↳ Keychron Keychron K15 Pro Consumer Control	id=22	[slave  keyboard (3)]
    ↳ Keychron Keychron K15 Pro System Control	id=23	[slave  keyboard (3)]
```

**Comment by Zireael07** [comment] 2024-04-24 07:32
The Any >> O is a debugging leftover (and worked properly)

The lines causing the problem are those two:

#F1 >> print["pressed the key", F1]
   
#  AltRight{A} >> 'ae'

if I uncomment them, I get Key name expected at... error

Yes I'm on Linux

**Comment by ristomatti** [comment] 2024-04-24 08:04
Did you comment out the other line that starts with `F1` when testing? You can only have one mapping per key in a section (or the implicit default section in the start).

**Comment by Zireael07** [comment] 2024-04-24 08:22
@ristomatti I don't remember - anyway if you can only have one mapping per key the error message should say that and not "Key name expected at..."

**Comment by ristomatti** [comment] 2024-04-24 10:30
If I edit this range like so:

```ini
# test chorded things
#log  = $(echo "$0" >> ~/tmp/keymapper.log)
print = $(echo $0 $1 >> ~\keymapper.txt)

# F1 >> $(echo F1 >> ~\keymapper.txt)

F1 >> print["pressed the key", F1]
   
AltRight{A} >> 'ae'
```

Config updates. Pressing `F1` prints `pressed the key F1` into a file named `~\keymapper.txt`.

Is the prefix `~\` intententional or did you mean to put `~/`. It might be your system is more sensitive to odd file names than mine(?)

**Comment by ristomatti** [comment] 2024-08-12 01:34
@houmain One vote from me. No activity tends to either means the issue went away, the OP found a different app that felt better suited or gave up altogether.

**Closed** 2024-08-16 06:34 UTC

**Comment by Zireael07** [comment] 2024-08-16 07:13
I missed the updates here somehow even though I'm watching the repo. Currently, as ristomatti correctly guessed, I am using a different app for my personal computer.
