### ISSUE TITLE
mapping shift to be shift or parenthesis

### ISSUE THREAD

**Issue by kbilsted** [houmain/keymapper#122] opened 2024-03-24 22:11 UTC
Inpired from the space cadet keyboard I I decided to try out remapping my Shift keys to work like so:

- When held while pressing other keys, act like Shift.
- When pressed and released on their own, type an opening or closing parenthesis (left and right shift respectively).

I have tried 
```
ShiftLeft{!200ms} >> '('
ShiftRight{!200ms} >> ')'
```

alas u i face some weird timing issues. Shift-t require me to hold down shift for a "long time" before pressing T. otherwise i get a `t` rather than a `T`. Other characters do not have the same issue.

Also when holding down shift and pressing `abc` I get `Abc` where I would have expected `ABC`. 

I then tried combining it with a `ShiftRight{Any}` but I think it only made matters worse.

What am I doing wrong?

**Comment by ristomatti** [comment] 2024-03-25 00:07
I'm pretty confident you'll be hitting some unexpected behavior if remapping shift-keys. With that said, try if this would work closer to what you want:

```ini
ShiftLeft{Any} >> ShiftLeft{Any}
ShiftRight{Any} >> ShiftRight{Any}
ShiftLeft{100ms} >> ShiftLeft
ShiftRight{100ms} >> ShiftRight
ShiftLeft >> '('
ShiftRight >> ')'
```

Personally I've done this instead (assuming US/UK layout):

```ini
AltRight{BracketLeft}                  >> !AltRight Shift{9} # '('
AltRight{BracketRight}                 >> !AltRight Shift{0} # ')'
```

It makes sense when using US/UK key layout. I can then get `[{(` and `)}]` all from the samt two keys.

**Comment by ristomatti** [comment] 2024-03-25 01:02
Slightly improved version that also supports `()`.

```ini
ShiftLeft !150ms ShiftRight >> '()'
ShiftLeft{ShiftRight} >> '()'
ShiftLeft{Any} >> ShiftLeft{Any}
ShiftRight{Any} >> ShiftRight{Any}
ShiftLeft{100ms} >> ShiftLeft
ShiftRight{100ms} >> ShiftRight
ShiftLeft >> '('
ShiftRight >> ')'
```

**Comment by kbilsted** [comment] 2024-03-25 10:06
Many thanks for your input. It has really bin a rollercoaster ride not only with this remapper tool, but also with so many other tools. They give off the impression you can do anything but remapping alt, shift - keys that screams for remapping you run into a ton of problems! There should be specific guides somewhere instructing you on how you go about remapping those keys. I see many mod CAPS key but I don't think it is an easy reach for me. 

I'm very interested in remapping all my special keys for programming, so ill look into your definitions. Im on a nordic keyboard. I guess it is also very editor dependent. My editor autocompletes ), }, ] for me, so thef are less critical. I like the feel when I remodded J-K as you read in an earlier post, but perhaps it will cause more grief over time.

Any thoughts on this approach that places all layers on ALT's https://github.com/Roman-/redblue/blob/main/img/main.png

**Comment by ristomatti** [comment] 2024-03-25 13:36
> It has really bin a rollercoaster ride not only with this remapper tool, but also with so many other tools

Tell me about it! Once you let the genie out of the bottle... I jumped ~5 months ago after receiving my first QMK enabled Keychron K3 Pro (ISO Nordic as well btw). It was quite a battle after using a ThinkPad Compact keyboard for the past 10 years. ThinkPad layout by itself was a lot more ergonomic, mainly because of it's shorter spacebar and reversed Fn/Control keys. It effectively had the thumb keys one letter closer which allowed reaching both Win and Alt key with my thumb. It took a month of fiddling with QMK to reach the same level of ergonomics.

At that point, I was pretty pleased with my setup. So pleased, that after I saw the release of Keychron K15 Pro (low profile, alice layout), I decided to take the plunge and order my first US ANSI keyboard (ISO Nordic not yet available)... Then it was time to start from the beginning to find the most practical way of using `ÄÖ` without changing the input language. :sweat_smile: 

Around that time I ran across [this article](https://medium.com/@canadaduane/key-remapping-in-linux-2021-edition-47320999d2aa) comparing Linux keymapping tools and found Keymapper. After receiving my K15 Pro, I thought I'll try if I could get away with Keymapper instead of QMK. Now ~4 months later, I've ended up using both (but mostly Keymapper). Recently I've also added [Espanso](https://espanso.org/) to the mix after a friend tipped about it. It neatly complements the setup with the hotstring feature I loved AutoHotkey for back when I used Windows (~12y ago).

It's been a period full of relaxing tweaking, pleasing outcomes, frustration and headaches. So many hours of work time lost during this quest, I for sure aren't going to get it "paid back" increased productivity :joy:. Now it's only about ergonomics, reducing friction (...and an obsession).

> Any thoughts on this approach that places all layers on ALT's

I don't think about  layers as much now with Keymapper as I do app specific remapping. With that said, I use Alt-keys in my remaps the most of the traditional mod-keys. I've got so small hands, using Control on it's normal place is only doable for ASDF/ZXCV keys. I've put it on Caps Lock but like you, I find it hard to reach and don't use it much.

For QMK layers, I've found Tab more comfortable. On the K3 Pro (ISO Nordic), I found these keys convenient for layers while allowing use of most shortcuts I was already using:

![image](https://github.com/houmain/keymapper/assets/9029939/9a1f4885-ca25-4fd5-b5c8-4975bc9d1292)

...I also put Esc in place of Å as it's not used in Finnish.

**Comment by houmain** [comment] 2024-03-26 09:30
@kbilsted It should work with your initial configuration. I think I know what's going wrong and how to fix it.

**Comment by houmain** [comment] 2024-04-10 18:38
Hi, with the latest commits this should work as expected:
```
ShiftLeft{!200ms} >> '('
ShiftRight{!200ms} >> ')'
```

**Comment by kbilsted** [comment] 2024-04-11 16:20
will test on latest version

**Comment by ristomatti** [comment] 2024-04-11 16:58
@kbilsted Try with:

```ini
ShiftLeft{!120ms}  >> '('
ShiftRight{!120ms} >> ')'
ShiftLeft{Any}     >> ShiftLeft{Any}
ShiftRight{Any}    >> ShiftRight{Any}
```

It will likely still mess up with any other mapping involving the shift keys if you have any. I'd confine this to apps where you need it regardless.

**Comment by houmain** [comment] 2024-04-11 17:22
Sorry, I thought you were building from source. With latest commits I meant the ones after 4.0.1. But I think they are worth creating a 4.0.2.

**Comment by ristomatti** [comment] 2024-04-11 18:09
You probably replied to @kbilsted but I usually am. This time I figured you were talking about the earlier changes.

P.S. What is the proper way of signaling CMake to disable Wayland support? I've hard coded it on the build file, committed that change and always rebase the new changes. It's beginning to feel silly.

**Comment by ristomatti** [comment] 2024-04-11 18:14
I've even created a [mise](https://mise.jdx.dev/) workspace config to simplify building, starting/stopping the installed version and running a freshly built version for testing. :joy:


![image](https://github.com/houmain/keymapper/assets/9029939/8be285b7-54e7-4500-978a-c4984c6f27f1)

**Comment by ristomatti** [comment] 2024-04-11 18:29
With 4.0.2 the workaround I suggested is not anymore necessary. Initially I was seeing a regression with some of the mouse mappings that you fixed with 4.0.1, but it seems like restarting `keymapper` fixed it. I'll run with it for some time to see if I run into some other issues.

If nothing breaks, this has a lot of potential to allow other use cases as well :crossed_fingers:!  I've reverted my changes back several times due to modifiers misbehaving futher down the config.

**Comment by kbilsted** [comment] 2024-04-12 14:00
The result is much better! but i can still easily make it print lower case when it should print upper!

with one hand steadily press the same key again and again. Then with the other press shift. hold it a while, release it and hold again fast 

```c#
    AAAAAAAAAAaaaaaaaaaa  AAAAAAAAAAAAAAAAAaaaaaaaaaa
              ^                  ^         ^
     arrow denote release and press shift
```

so not all the time but frequent when you use shift and a letter fast in succession it become lowercase

**Comment by ristomatti** [comment] 2024-04-12 16:21
I noticed the same. Also it seemed that when it occurred, I had to do `SpaceLeft`, `SpaceRight` multiple times to get `()`, after which they worked again. Like the bindings would've been moved out of cache or something. Then again, my config is really complex and at the time I had 4 input devices at the same time with device specific configs. I had just added this novelty to the mix https://www.aliexpress.com/item/1005006099525907.html (bought mainly for decoration, space around my keyboard is reserved to mice for both hands). :slightly_smiling_face:

**Comment by houmain** [comment] 2024-04-12 17:51
Thanks for the feedback. The last commit should at least fix the phenomenon described by @kbilsted.

@ristomatti I would love to see a photo of your desktop when everything is deployed. 😂

**Comment by kbilsted** [comment] 2024-04-12 19:35
@houmain  perhaps @ristomatti has watched too many cyberpunk movies :)

**Comment by ristomatti** [comment] 2024-04-12 23:32
> @ristomatti I would love to see a photo of your desktop when everything is deployed. 😂

"Deployed" :rofl:

Here we go:

![deskie](https://github.com/houmain/keymapper/assets/9029939/2683ac8a-28cd-4ac9-8068-a17998e61061)

**Comment by houmain** [comment] 2024-04-13 17:21
Making good use of two mice is already quite impressive!

**Comment by ristomatti** [comment] 2024-04-13 19:37
I've had RSI more than once. It balances a little bit. For the same reason I'm also using the lightest switches I could find, [Gateron NuPhy Aloe](https://nuphy.com/products/nuphy-aloe-l37-low-profile-switches)'s. They've got opering force of only 37±15gf. It took "a bit" of type to not typo every other word. but after that, these have been an absolute breeze to use. I tried going with the stock red switches but after just 2-3 weeks I started getting wrist pain.

**Comment by kbilsted** [comment] 2024-04-13 20:25
have you tried https://www.maxgaming.dk/dk/switchar/choc-low-profile-pink-pro  i want a glove 80 with red pro i think i'll enjoy flat and light

**Comment by ristomatti** [comment] 2024-04-13 21:27
AFAIK only Gateron's low profile switches are compatible with Keychron's low profile models. I've got the K3 Pro as well, so I think I'll confine myself to ones that are compatible. Besides, I really like stock keycaps as well. I did order two sets of hopefully compatible keycaps from AliExpress for my K3 Pro. My plan is to convert it to ISO UK layout now that I've gotten used to ANSI US on this split keyboard.

20g sounds insaly light thought. Prior to my jump to mech keyboards half a year ago, I had used Lenovo ThinkPad Compact TrackPoint keyboards (and to some extent ThinkPad integrated keyboards) for maybe 8 years. The 50±15 gf of Gateron Red switches felt really stiff compared to [39gf of the ThinkPad switches](https://www.rtings.com/keyboard/reviews/lenovo/thinkpad-trackpoint-keyboard-ii#test_3377). I've got small and relatively dexterous fingers/hands but IO was surprised how light the Aloe's were. It really felt like ice scating for the first weeks :joy:.

Personally I think I could like Gateron's optical white switches available for the non-pro Keychron K-series models though:

![image](https://github.com/houmain/keymapper/assets/9029939/e05bba19-4f56-4011-af75-b243a7a062cf)

Unfortunately QMK firmware does not support optical switches even though they'd otherwise fit (or at least this is what I've read).

**Comment by houmain** [comment] 2024-04-17 17:40
> Thanks for the feedback. The last commit should at least fix the phenomenon described by @kbilsted.

Hi, this is finally easily testable in the 4.1.0 release.

**Comment by kbilsted** [comment] 2024-04-17 18:56
I hope it works this time.  Tell me when ready

**Comment by houmain** [comment] 2024-04-19 15:41
> I hope it works this time. Tell me when ready

Well, it is.

**Comment by ristomatti** [comment] 2024-04-19 21:29
I found this to work pretty much perfectly a few hours of actual work but the mapping itself didn't work out well with my workflow, so I decided to continue using my old way of

```ini
AltGr = AltRight
AltGr{BracketLeft} >> Shift{9}
AltGr{BracketRight} >> Shift{0}
```

Aside, I want to say version 4.1 has so far worked stellar (besides the few "cosmetic" issues discussed at #126 and #131). It really shows you know what you're doing. Despite my non-existant C++ skills, I've read and written enough to say the codebase looks very "clean" and well thought out. May I ask how long you've been writing C++, is it something you do for work as well and if so, what type of industry? I'm guessing game development based on your other repos. 🙂

**Comment by ristomatti** [comment] 2024-04-19 21:50
...to continue on the previous comment, I just today noticed this [inverse condition syntax](https://github.com/houmain/keymapper/commit/3b57e3f12c4ace5e9d18fcf3202c25a4998bdbef#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R120) has appeared and found use to it right away.

I also noticed aliases within parameterized aliases now work as well I mentioned on some other issue thread. Just this evening I added this section to streamline Tmux pane and window navigation (I've included some other related parts here):

```ini
# Key groups
Digit           = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9

# Directional navigation
KeyUp           = I
KeyLeft         = J
KeyDown         = K
KeyRight        = L
Direction       = KeyUp | KeyLeft | KeyDown | KeyRight

# Class matchers
Terminal        = /kitty|tmux/i

# Passtrough common modifiers
[default]
  AltLeft       >> AltLeft
  AltRight      >> AltRight
  ControlLeft   >> ControlLeft

[class != Terminal title != "tmux"]
  ControlRight  >> ControlRight

# Terminal // Tmux
[class = Terminal title = "tmux"]
  TmuxMod     = Tab
  TmuxTap     = Tap[ControlRight]

  # Bindings used in tmux.conf
  TmuxBinding = Direction | N | P | O | W | Comma | Period | Digit

  TmuxPrefix  = !TmuxMod (ControlRight A){10ms} 10ms $0
  
  # Navigate with Tab+X
  TmuxMod{TmuxBinding}  >> TmuxPrefix[TmuxBinding]
  
  # Navigate with Control followed by X
  TmuxTap TmuxBinding   >> TmuxPrefix[TmuxBinding]

  ControlRight          >> ControlRight
```

**Comment by ristomatti** [comment] 2024-04-19 22:01
For the curious, I've just updated my public (slightly redacted) gist of the full config [here](https://gist.github.com/ristomatti/7295775781ad697bd274bad858427281).

**Comment by ristomatti** [comment] 2024-04-20 19:57
Last night I noticed I had also missed the "optional comma" within context definitions. It's like you've read my thoughts on this one, or did you spot it from some screenshot I've posted. Just recently changed the `ContextActive` enter/leave logs to look like this:

![image](https://github.com/houmain/keymapper/assets/9029939/51637238-2c99-4d34-877d-002fac6c3382)

After I spot the change, I immediately reformatted all the context blocks to use the new `[class = /foo|bar/i, title = "baz"]` format. It's so much easier to read. :+1:

**Comment by houmain** [comment] 2024-04-23 15:51
> For the curious, I've just updated my public (slightly redacted) gist of the full config [here](https://gist.github.com/ristomatti/7295775781ad697bd274bad858427281).

The configuration is very impressive! May I add a reference to it in the examples section of the README?

**Comment by ristomatti** [comment] 2024-04-23 21:41
@houmain I'd be honored. I'm considering moving it into a repository at some point. I could then include the (mostly i3wm related) scripts used within the config (`i3-open`, `redshiftctl` and the virtual modifier state indicators). Not sure when I'll have the time though. I might wait until you've added support for splitting the config into smaller files. :wink:. During the weekend I already started drafting a discussion thread about it to throw in some ideas. I'll post it later though as I got interrupted midway...

I've just updated the gist again. My decorative Apayado K33 Numpad got some new skills:

- `ScrollLock` activates `NavMode` in which it can be used to switch to specific workspaces, goto next/prev workspace, show/hide specific scratchpad windows, tab through scratchpad windows
- In `NavMode` pressing `ArrowUp` opens Rofi notifition menu and activates `RofiMode`, while holding down `ArrowDown` can be used to "peek" notifications. When in `RofiMode`, navigation/editing keys work normally so notifications can be deleted etc.
- At any time, presssing `NumLock` opens a calculator and allows normal use as a numpad. Pressing `NumLock` again exits calculator

Naturally most of that is just playing around, but I've actually used the calculator mode multiple times, so it's definitely a keeper.

**Comment by ristomatti** [comment] 2024-04-23 22:38
> Well the code was not always that nice, but it was refactored a few times since the first version I created around 2011. 🙂

I'm impressed, you've been very persistent! I thought the work has started around the first commits on the repo. That's a long time. Based on the first commits on my (private) dotfiles repo, I've started building my Vim config just around 2015 😄. (Sidenote: early this year I tried moving over to Neovim as my config file/script editor. It was really frustrating, then I found Helix and it's now my default editor :grin:)

> I think it was superseded by programming applications which make my and hopefully also other people's lives more comfortable.

It definitely has! I am baffled how this repo can have so little stars. `kmonad` has been published only a little earlier for instance and it's got 3.5k. I'm thinking somehow people just aren't aware Keymapper exists. You might get a flood of users if someone posts this on Hacker News. Interestingly only a few posts come up with the search https://hn.algolia.com/?q=keymapper. Even more interestingly, there's one on [sezanzeb/key-mapper)](https://github.com/sezanzeb/key-mapper) and the post has only got 2 points. The repo now has 3.3k stars. :thinking: 

> Did you also notice that a context block can have multiple headers now? This was another new context feature and is scarcely documented (they were also mentioned in the 4.0.0 changelog):

I did not! You ought to advertise these a bit more. I wonder what other features I've missed already...

Are you still up to receiving more feature requests? I've got a few ideas besides the already mentioned config file splitting (which I could as well do by myself by introducing a "build" step). They should not be as involved as `keymapperctl` and the related other stuff! Two are inconveniences related to handling of abstract commands for instance.

**Comment by houmain** [comment] 2024-04-24 17:35
> I might wait until you've added support for splitting the config into smaller files. 😉.

I still have it on my list and will try to add it some time.

> Are you still up to receiving more feature requests?

Of course! Your input has been very valuable.

> I found this to work pretty much perfectly

Ok, thanks, then I will close this issue.

**Closed by houmain** 2024-04-24 17:35 UTC

**Comment by ristomatti** [comment] 2024-04-24 18:30
> I still have it on my list and will try to add it some time.

I'll try to find time on the weekend to post my initial thoughts/ideas on it in the discussion area.

**Comment by kbilsted** [comment] 2024-04-24 20:37
version 4.1.1 works very well with the timings on windows. Thanks and sorry for not replying sooner!
