### ISSUE TITLE
Add support for mouse left and right scroll wheel buttons

### ISSUE THREAD

**Issue by tonyatpeking** [houmain/keymapper#169] opened 2024-08-23 16:25 UTC
I have a Logitech M510 mouse, that has left and right scroll wheel button (also found on many other mice). I would like to be able to remap these.

See image, there are arrows like < that indicate that you can push the scroll wheel slightly to the left and right to push the buttons:

<img src="https://github.com/user-attachments/assets/18ca47c2-c963-49a4-af76-c309b21e5343" width="300">

 
They function as normal buttons (under the hood the hardware is just a normal mouse micro switch)

Running `evtest` and pushing the buttons give the following for the relevant keys:

Left Scroll:

```
type 2 (EV_REL), code 6 (REL_HWHEEL), value -1
type 2 (EV_REL), code 12 (REL_HWHEEL_HI_RES), value -120
```

Right Scroll:

```
type 2 (EV_REL), code 6 (REL_HWHEEL), value 1
type 2 (EV_REL), code 12 (REL_HWHEEL_HI_RES), value 120
```

Running on X11
Also have a windows machine and willing to test stuff there as well.

I am aware of Solaar and other options but would rather have all my key maps in one place (keymapper)

P.S. Awesome project, came for the cross platform support, really like the idea that I can have unified shortcuts for Win and Linux

**Comment by ristomatti** [comment] 2024-08-24 04:18
Fail. I had forgot the buttons exist when submitting #110. Likely because I only use them maybe once or twice a year :man_facepalming:.... They'd definitely turn more useful with remapping (e.g. `WheelLeft >> previous_tab`). 

Hopefully it'd be as small of a change I'd expect it to be since wheel up/down has already been added (and side effects caused by that found and fixed). :crossed_fingers:

**Comment by ristomatti** [comment] 2024-08-24 04:34
Note: I've had the wheel left/right buttons on at least the 4 most recent Logitech mise I've bought: Performance MX, MX Anywhere, MX Anywhere S2, G502 Ligthspeed). The first two were released 2009. They're also typically mapped to button 6 (left) and 7 (right) AFAIK.

**Comment by houmain** [comment] 2024-08-24 10:10
Hi, this is already testable in 4.7.2.
While testing it myself (as far as I could without such a device) I noticed that the `WheelUp` and `WheelDown` were swapped on Windows. So this should also be fixed now.

**Comment by tonyatpeking** [comment] 2024-08-26 13:27
Tested and works for me. X11 Ubuntu. Very happy.

**Comment by ristomatti** [comment] 2024-08-27 02:39
Confirm working also. This will get a lot of use! :rocket:

**Comment by tonyatpeking** [comment] 2024-08-27 17:50
Change seems to have broken some things. (should I create a new issue or just use this one?)

On Ubuntu 24.04 X11

How to reproduce:

in keymapper.conf:

`WheelLeft >> "LEFT"`      (map WheelLeft to output "LEFT")
`? "qq" >> "Matched!"`     (map qq to output Matched! )

Input:
`> qq`
qMatched!   (as expected)
`> (press mouse WheelLeft button)`
LEFT  (as expected)
`> qq`
qq      (WheelLeft seems to have broken the ? "qq" matching)

**Comment by ristomatti** [comment] 2024-08-27 19:48
I can reproduce. In fact @houmain I've noticed that even before this update, the `? 'xyz` mappings stop working after some time. They start working again after touching the config file to trigger a reload.

@tonyatpeking Do you have everything in one file or using `@include`? I was wondering if this issue could've been related to to moving the mappings outside of the main config, but I'm thinking now that it's related to this.

**Comment by tonyatpeking** [comment] 2024-08-28 13:37
@ristomatti The bug is reproducible with an empty keymapper.conf with just these two lines:

`WheelLeft >> "LEFT"`
`? "qq" >> "Matched!"`

So my bet is that it has nothing to do with `@include`
I actually found the bug when I was testing your `text_expansion.conf` for email completions. I'm guessing this is also how you encountered the bug.

**Comment by ristomatti** [comment] 2024-08-28 21:11
I also noticed that preventing key repeat does not work. Holding `WheelLeft/Right` will zip through all the tabs. It might also be that the mouse (or the driver) sends the event repeatedly, in which case I wouldn't consider this a bug. It doesn't happen quickly either so it's not a big issue.

```starlark
WheelLeft  >> prev_tab
WheelRight >> next_tab

prev_tab >> !Any Control{PageUp} ^
next_tab >> !Any Control{PageDown} ^
```

Timings do not seem to work either. I tried something like below, but holding the wheel just changes the tabs rapidly.

```starlark
WheelLeft{200ms} >> WheelLeft
WheelRight{200ms} >> WheelRight

WheelLeft  >> prev_tab
WheelRight >> next_tab
```

I also tried the inverse with the same result:

```starlark
WheelLeft{!200ms} >> prev_tab
WheelRight{!200ms} >> next_tab

WheelLeft  >> WheelLeft
WheelRight >> WheelRight
```

**Comment by houmain** [comment] 2024-08-31 08:10
@tonyatpeking this should be fixed with the 4.7.3 release.

>> It might also be that the mouse (or the driver) sends the event repeatedly, in which case I wouldn't consider this a bug.

Yes, right. That's because it is a wheel and not a button. There is nothing like a Wheel-Stop event.
But this should work:
```
WheelLeft 200ms >> prev_tab
WheelRight 200ms >> next_tab
```

**Comment by tonyatpeking** [comment] 2024-08-31 20:36
Tested 4.7.3 and works for me.

**Comment by ristomatti** [comment] 2024-09-01 00:54
> Yes, right. That's because it is a wheel and not a button. There is nothing like a Wheel-Stop event. But this should work:
> 
> ```
> WheelLeft 200ms >> prev_tab
> WheelRight 200ms >> next_tab
> ```

It does make make then "zip through tabs" issue slower to occur but still doesn't allow triggering the scroll event if held down longer. But if there is no key up event, it doesn't sounds too brittle to try to workaround. Regardless, it's a net gain at least. It's increasingly rare to encounter a web page that forces me to scroll sideways.. Meanwhile my intereet in staying on such pages is decreasing at the same rate. :grin:

**Comment by houmain** [comment] 2024-09-01 09:01
Yes, the configuration I posted was just meant as a fix for the "zip through tabs" issue.

**Closed by houmain** 2024-09-01 09:01 UTC
