### ISSUE TITLE
Input Devices keeps disconnecting and reconnecting

### ISSUE THREAD

**Issue by medanimohamedakram** [houmain/keymapper#149] opened 2024-05-23 04:44 UTC
when I upgraded to 4.2.0
Mouse and keyboard kept lagging and I noticed the numlock and Caps kept flashing as if connecting and disconnecting continously 
I downgraded to 4.1.3 and every turned back to normal

I tried building from source to the latest commit but the issue still persist

**Comment by houmain** [comment] 2024-05-26 18:53
Thanks for reporting!
Was it possibly caused by a still running, not updated `keymapperd` instance being incompatible with the updated `keymapper` instance? Or the other way round. 
Could you stop both before installing the new version? (`sudo systemctl stop keymapperd`, `killall keymapper`)
I will add a version check, which should detect this problem and exit with an error message.
If that was not the cause, could you please start them manually with the verbose flag and post the output. (`sudo keymapperd -v`, `keymapper -v`). 
Thanks!

**Comment by ristomatti** [comment] 2024-05-26 19:39
I had a similar issue after upgrade which got fixed by restarting `keymapperd`. This check sounds like a good idea. I don't know feasible this is but I think even better would be if `keymapperd` would be forced to restart after an upgrade. This is not how upgrades are normally handled on Linux, but I could see this as an exception due to the tight coupling between the processes.

**Comment by ristomatti** [comment] 2024-05-26 19:43
...after a bit of thinking, that would be a very bad idea as the upgrades could have breaking changes 😅. A warning is much better.

**Comment by medanimohamedakram** [comment] 2024-05-26 21:09
> Thanks for reporting!
> Was it possibly caused by a still running, not updated `keymapperd` instance being incompatible with the updated `keymapper` instance? Or the other way round. 
> Could you stop both before installing the new version? (`sudo systemctl stop keymapperd`, `killall keymapper`)
> I will add a version check, which should detect this problem and exit with an error message.
> If that was not the cause, could you please start them manually with the verbose flag and post the output. (`sudo keymapperd -v`, `keymapper -v`). 
> Thanks!

I tried this  and it seems that was the issue 
So keymapper works fine now, Thanks

**Closed** 2024-06-15 17:12 UTC
